apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        tier: client
    spec:
      containers:
      - image: zozoh94/flask-vue-client:v1.1
        name: client
        ports:
        - containerPort: 80