apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: zozoh94/flask-vue-init:v1.1
        env:        
          - name: POSTGRES_HOST
            value: "postgres"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
      restartPolicy: Never
  backoffLimit: 4
  
